services:
  java-spring-server:
    container_name: java-spring-server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - CR_HOST=opencv-python-server
      - CR_PORT=8081
      - OPTIMIZER_HOST=minizinc-python-server
      - OPTIMIZER_PORT=9091
      - CR_PASSWORD=1234
      - OT_PASSWORD=4321
      - OPTIMIZATION_TIME_PERIOD_SCALING=3
      - BUS_MULTIPLIER=3
    networks:
      - tfo-net
    ports:
      - 8080:8080
    restart: always

networks:
  tfo-net:
    external: true