services:
  java-spring-server:
    container_name: java-spring-server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - OPTIMIZER_HOST=minizinc-python-server
      - OPTIMIZER_PORT=9091
    networks:
      - tfo-net
    ports:
      - 8080:8080
    restart: always

networks:
  tfo-net:
    external: true